Fixed compile warning/error with g++ version 4.8
I believe the intention was to initialize with the_R instead of R,
though I don't use this functionality so the change is untested.

The warning/error was as follows:
AddOns/Domains/Source/wali/domains/lh/PhaseLH.cpp: In constructor 'wali::domains::lh::PhaseLH::PhaseLH(bdd, int)':
AddOns/Domains/Source/wali/domains/lh/PhaseLH.cpp:808:1: error: 'wali::domains::lh::PhaseLH::R' is initialized with itself [-Werror=init-self]
 PhaseLH::PhaseLH( bdd the_R,int the_phaseX ) : R(R),phaseX(the_phaseX)
 ^
cc1plus: all warnings being treated as errors